/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brezenhem;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;


public class MyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyJFrame
     */
    public MyJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCanvas = new javax.swing.JPanel();
        jtfX1 = new javax.swing.JTextField();
        jtfY1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBrezenhem = new javax.swing.JButton();
        jtfX2 = new javax.swing.JTextField();
        jtfY2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCanvas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelCanvasLayout = new javax.swing.GroupLayout(jPanelCanvas);
        jPanelCanvas.setLayout(jPanelCanvasLayout);
        jPanelCanvasLayout.setHorizontalGroup(
            jPanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanelCanvasLayout.setVerticalGroup(
            jPanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        jtfX1.setText("0");
        jtfX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfX1ActionPerformed(evt);
            }
        });

        jtfY1.setText("0");

        jLabel1.setText("X1:");

        jLabel2.setText("Y1:");

        btnBrezenhem.setFont(new java.awt.Font("mononoki", 1, 24)); // NOI18N
        btnBrezenhem.setText("Brezenhem");
        btnBrezenhem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrezenhemActionPerformed(evt);
            }
        });

        jtfX2.setText("0");
        jtfX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfX2ActionPerformed(evt);
            }
        });

        jtfY2.setText("0");

        jLabel3.setText("X2:");

        jLabel4.setText("Y2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBrezenhem, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfX2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfX1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfY2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfY1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnBrezenhem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    
    private void jtfX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfX1ActionPerformed
        
    }//GEN-LAST:event_jtfX1ActionPerformed

    private void btnBrezenhemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrezenhemActionPerformed
        Graphics g=jPanelCanvas.getGraphics();
        
        g.drawLine(0,0,jPanelCanvas.getWidth(),jPanelCanvas.getHeight());
        g.drawLine(0,jPanelCanvas.getHeight(),jPanelCanvas.getWidth(),0);
        g.setColor(Color.red);
        
        int x1, x2, y1, y2, // linijas sakuma un beiguma punkti
                xn, yn,     // iteratori
                xi, yi,     // soli
                pn,         // risinosais parametrs
                dx, dy,     // projekcijas garumi
                i;          // ???
        x1=Integer.parseInt(jtfX1.getText());
        y1=Integer.parseInt(jtfY1.getText());
        x2=Integer.parseInt(jtfX2.getText());
        y2=Integer.parseInt(jtfY2.getText());
        i=0;
        xn=x1; 
        yn=y1; 
        dx=Math.abs(x2-x1);
        dy=Math.abs(y2-y1);
        // atkariba no ta, vai linija aug vai dilst, aprekinam solus
        xi=x2>x1?1:-1;
        yi=y2>y1?1:-1;
        
        // ievietot pirmo pikseli
        drawPixel(xn,yn,g);
        
        // Atkariba no dx un dy izmantojam dazadu risinoso parametru un asi
        if(dx>=dy){
            // идём по оси Х (У изменяется интенсивнее, чем Х =>
            // => У одного Х будет только один У
            
            // Определяем Risinosais parametrs
            pn=2*dy-dx;    

            while (xn!=x2){
                if (pn>=0){
                    xn=xn+xi;
                    yn=yn+yi;
                    pn=pn+2*dy-2*dx;
                    i++;
                } else {
                    xn=xn+xi;
                    pn=pn+2*dy;
                    i++;
                }
                drawPixel(xn,yn,g);
//                g.drawRect(xn,yn,2,2);
              }
        }
        // ja pn>=0, tad d1>=d2
        if(dy>dx){
            // т.к. проекция на оси У больше чем проекция на Х
            // , то у одного Х может быть несколько У
            // => идём по оси У
            // Это лучше чем идти по Х определять, нужно ли нам его увеличивать
            
            // Определяем Risinosais parametrs
            pn=2*dx-dy;

            while(yn!=y2){
              if (pn>=0){
               xn=xn+xi;
               yn=yn+yi;
               pn=pn+2*dx-2*dy;
               i++;

              }else{
               yn=yn+yi;
               pn=pn+2*dx;
               i++;


              }
              drawPixel(xn,yn,g);
//              g.drawRect(xn,yn,2,2);

            }
        }
        
    }//GEN-LAST:event_btnBrezenhemActionPerformed

    private void jtfX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfX2ActionPerformed
        
    /** Helper methods that draws single pixels by using drawLine() method */
    private void drawPixel(int x,int y, Graphics g){
        g.drawLine(x,y,x,y);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrezenhem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelCanvas;
    private javax.swing.JTextField jtfX1;
    private javax.swing.JTextField jtfX2;
    private javax.swing.JTextField jtfY1;
    private javax.swing.JTextField jtfY2;
    // End of variables declaration//GEN-END:variables
}
