/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstprogram;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;


public class MyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyJFrame
     */
    public MyJFrame() {
        initComponents();
        mGraphics=jPanelCanvas.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonShowImage = new javax.swing.JButton();
        jPanelCanvas = new javax.swing.JPanel();
        JTextFieldLinesNumber = new javax.swing.JTextField();
        jButtonShowLength = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLines = new javax.swing.JTextArea();
        btnShowPixels = new javax.swing.JButton();
        btnShowSinus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonShowImage.setFont(new java.awt.Font("mononoki", 1, 24)); // NOI18N
        jButtonShowImage.setText("Show Image");
        jButtonShowImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowImageActionPerformed(evt);
            }
        });

        jPanelCanvas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelCanvasLayout = new javax.swing.GroupLayout(jPanelCanvas);
        jPanelCanvas.setLayout(jPanelCanvasLayout);
        jPanelCanvasLayout.setHorizontalGroup(
            jPanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanelCanvasLayout.setVerticalGroup(
            jPanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        jButtonShowLength.setFont(new java.awt.Font("mononoki", 1, 24)); // NOI18N
        jButtonShowLength.setText("Show Lines");
        jButtonShowLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowLengthActionPerformed(evt);
            }
        });

        jTextAreaLines.setColumns(20);
        jTextAreaLines.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLines);

        btnShowPixels.setFont(new java.awt.Font("mononoki", 1, 24)); // NOI18N
        btnShowPixels.setText("Show Pixels");
        btnShowPixels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPixelsActionPerformed(evt);
            }
        });

        btnShowSinus.setFont(new java.awt.Font("mononoki", 1, 24)); // NOI18N
        btnShowSinus.setText("Show Sin");
        btnShowSinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonShowImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTextFieldLinesNumber)
                    .addComponent(jButtonShowLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnShowPixels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowSinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonShowImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTextFieldLinesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonShowLength, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowPixels, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowSinus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowImageActionPerformed
//        Graphics myGraphics = this.jPanelCanvas.getGraphics();  
        
        mGraphics.drawLine(0,0,jPanelCanvas.getWidth(),jPanelCanvas.getHeight());
        
        mGraphics.drawLine(0,jPanelCanvas.getHeight(), jPanelCanvas.getWidth(),0);
        
        // or
//        Point p1=new Point(0,0);
//        Point p2=new Point(jPanelCanvas.getWidth(),jPanelCanvas.getHeight());
//        mGraphics.drawLine(p2,p1);
        
    }//GEN-LAST:event_jButtonShowImageActionPerformed

    private void jButtonShowLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowLengthActionPerformed
        
        int lineNumber=Integer.parseInt(this.JTextFieldLinesNumber.getText());
        
        for(int i=0;i<lineNumber;i++){
            mGraphics.drawLine(10*i, 0, 10*i, jPanelCanvas.getHeight());
            jTextAreaLines.append(String.format("Num: %d x0: %d y0 %d\n", i+1,10*i,0));
        }
        
    }//GEN-LAST:event_jButtonShowLengthActionPerformed
    
    private void btnShowPixelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPixelsActionPerformed
        drawPixel(100,100);
        
        int x=0;
        int y=200;
        
        while(x<400){
            if(x>200){
                y--;
            }else{
                y++;
            }
            drawPixel(x++,y);
        }
    }//GEN-LAST:event_btnShowPixelsActionPerformed

    private void btnShowSinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSinusActionPerformed
        drawPixel(100,100);
        
        // set draw color
        mGraphics.setColor(Color.RED);
        
        int x=0;
        int y=10;
        
        int offsetY=100;
        
        float radians=0;
        int amp =50; //amplituda
        float result = 0;
        
        while(radians<jPanelCanvas.getWidth()){
           radians+=0.05;
           x++;
           
           result=amp*(float)Math.sin(radians);
           
           y=Math.round(result+offsetY);
           
           drawPixel(x,y);
        }
    }//GEN-LAST:event_btnShowSinusActionPerformed

    /** Helper methods that draws single pixels by using drawLine() method */
    private void drawPixel(int x,int y){
        mGraphics.drawLine(x,y,x,y);
    }
    
    // Instantiate Graphics once, to avoid doing it in every event
    private Graphics mGraphics;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldLinesNumber;
    private javax.swing.JButton btnShowPixels;
    private javax.swing.JButton btnShowSinus;
    private javax.swing.JButton jButtonShowImage;
    private javax.swing.JButton jButtonShowLength;
    private javax.swing.JPanel jPanelCanvas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLines;
    // End of variables declaration//GEN-END:variables
}
